# Generated by tools/gen_final.py
scoreboard players add @a[tag=gl_green] gl_t_green 0
scoreboard players remove @a[scores={gl_t_green=1..}] gl_t_green 1
tag @a[tag=gl_green,scores={gl_t_green=..0}] remove gl_green
scoreboard players add @a[tag=gl_yellow] gl_t_yellow 0
scoreboard players remove @a[scores={gl_t_yellow=1..}] gl_t_yellow 1
tag @a[tag=gl_yellow,scores={gl_t_yellow=..0}] remove gl_yellow
scoreboard players add @a[tag=gl_red] gl_t_red 0
scoreboard players remove @a[scores={gl_t_red=1..}] gl_t_red 1
tag @a[tag=gl_red,scores={gl_t_red=..0}] remove gl_red
scoreboard players add @a[tag=gl_orange] gl_t_orange 0
scoreboard players remove @a[scores={gl_t_orange=1..}] gl_t_orange 1
tag @a[tag=gl_orange,scores={gl_t_orange=..0}] remove gl_orange
scoreboard players add @a[tag=gl_blue] gl_t_blue 0
scoreboard players remove @a[scores={gl_t_blue=1..}] gl_t_blue 1
tag @a[tag=gl_blue,scores={gl_t_blue=..0}] remove gl_blue
scoreboard players add @a[tag=gl_violet] gl_t_violet 0
scoreboard players remove @a[scores={gl_t_violet=1..}] gl_t_violet 1
tag @a[tag=gl_violet,scores={gl_t_violet=..0}] remove gl_violet
scoreboard players add @a[tag=gl_indigo] gl_t_indigo 0
scoreboard players remove @a[scores={gl_t_indigo=1..}] gl_t_indigo 1
tag @a[tag=gl_indigo,scores={gl_t_indigo=..0}] remove gl_indigo
scoreboard players add @a[tag=gl_white] gl_t_white 0
scoreboard players remove @a[scores={gl_t_white=1..}] gl_t_white 1
tag @a[tag=gl_white,scores={gl_t_white=..0}] remove gl_white
scoreboard players add @a[tag=gl_black] gl_t_black 0
scoreboard players remove @a[scores={gl_t_black=1..}] gl_t_black 1
tag @a[tag=gl_black,scores={gl_t_black=..0}] remove gl_black
tag @a[tag=gl_ring] remove gl_ring
tag @a[tag=gl_green] add gl_ring
tag @a[tag=gl_yellow] add gl_ring
tag @a[tag=gl_red] add gl_ring
tag @a[tag=gl_orange] add gl_ring
tag @a[tag=gl_blue] add gl_ring
tag @a[tag=gl_violet] add gl_ring
tag @a[tag=gl_indigo] add gl_ring
tag @a[tag=gl_white] add gl_ring
tag @a[tag=gl_black] add gl_ring
execute as @a unless score @s gl_id matches 1.. run function final_lanterns:id/assign
execute as @a[tag=!gl_hasid] run function final_lanterns:id/migrate
execute as @a at @s run function final_lanterns:ring/bind_check
execute if score #second gl_cfg matches 5 as @a[tag=gl_ring] at @s run function final_lanterns:ring/serial_check
execute if score #second gl_cfg matches 15 as @a[tag=gl_ring] at @s run function final_lanterns:ring/serial_check
execute if score #second gl_cfg matches 0 as @a at @s run function final_lanterns:ring/carry_check
execute if score #second gl_cfg matches 10 as @a at @s run function final_lanterns:ring/carry_check
execute as @a[scores={gl_recall=1..}] at @s run function final_lanterns:recall/trigger
scoreboard players set @a[scores={gl_recall=..-1}] gl_recall 0
execute as @a[tag=gl_offer_any] at @s run function final_lanterns:offer/follow
execute as @a[scores={gl_accept=1..}] at @s run function final_lanterns:offer/accept_trigger
execute as @a[scores={gl_decline=1..}] at @s run function final_lanterns:offer/decline_trigger
execute as @a[scores={gl_revoke=1..}] at @s run function final_lanterns:leader/revoke_trigger
execute as @a[scores={gl_roster=1..}] run function final_lanterns:leader/roster_trigger
execute as @e[type=minecraft:item_display,tag=gl_leave_go] at @s run tp @s ~ ~0.6 ~
scoreboard players remove @e[type=minecraft:item_display,tag=gl_leave_go] gl_tmp 1
kill @e[type=minecraft:item_display,tag=gl_leave_go,scores={gl_tmp=..0}]
scoreboard players add #second gl_cfg 1
execute if score #second gl_cfg matches 20.. run function final_lanterns:second
execute as @a[tag=!gl_rolled] run function final_lanterns:emotion/roll
execute as @a[scores={gl_emotions=1..}] run function final_lanterns:emotion/trigger
execute as @e[type=minecraft:item_display,tag=gl_entm_ion,tag=!gl_entm_grown] run function final_lanterns:entity/ion/grow
execute if score #state_ion gl_ent matches 1 as @e[tag=gl_ent_ion] at @s run function final_lanterns:entity/ion/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_parallax,tag=!gl_entm_grown] run function final_lanterns:entity/parallax/grow
execute if score #state_parallax gl_ent matches 1 as @e[tag=gl_ent_parallax] at @s run function final_lanterns:entity/parallax/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_butcher,tag=!gl_entm_grown] run function final_lanterns:entity/butcher/grow
execute if score #state_butcher gl_ent matches 1 as @e[tag=gl_ent_butcher] at @s run function final_lanterns:entity/butcher/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_ophidian,tag=!gl_entm_grown] run function final_lanterns:entity/ophidian/grow
execute if score #state_ophidian gl_ent matches 1 as @e[tag=gl_ent_ophidian] at @s run function final_lanterns:entity/ophidian/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_adara,tag=!gl_entm_grown] run function final_lanterns:entity/adara/grow
execute if score #state_adara gl_ent matches 1 as @e[tag=gl_ent_adara] at @s run function final_lanterns:entity/adara/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_predator,tag=!gl_entm_grown] run function final_lanterns:entity/predator/grow
execute if score #state_predator gl_ent matches 1 as @e[tag=gl_ent_predator] at @s run function final_lanterns:entity/predator/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_proselyte,tag=!gl_entm_grown] run function final_lanterns:entity/proselyte/grow
execute if score #state_proselyte gl_ent matches 1 as @e[tag=gl_ent_proselyte] at @s run function final_lanterns:entity/proselyte/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_life,tag=!gl_entm_grown] run function final_lanterns:entity/life/grow
execute if score #state_life gl_ent matches 1 as @e[tag=gl_ent_life] at @s run function final_lanterns:entity/life/tick
execute as @e[type=minecraft:item_display,tag=gl_entm_nekron,tag=!gl_entm_grown] run function final_lanterns:entity/nekron/grow
execute if score #state_nekron gl_ent matches 1 as @e[tag=gl_ent_nekron] at @s run function final_lanterns:entity/nekron/tick
execute as @a[scores={gl_entity=1..}] run function final_lanterns:entity/trigger
execute as @a[predicate=final_lanterns:entity/sneaking,predicate=final_lanterns:entity/holding_battery] at @s if entity @a[tag=gl_host,distance=0.1..6] run function final_lanterns:entity/exorcise
scoreboard players set @a[scores={gl_exo=1..},predicate=!final_lanterns:entity/sneaking] gl_exo 0
scoreboard players set @a[scores={gl_exo=1..},predicate=!final_lanterns:entity/holding_battery] gl_exo 0
scoreboard players remove @e[tag=gl_boss_minion] gl_life 1
execute at @e[tag=gl_boss_minion,scores={gl_life=..0}] run particle minecraft:soul ~ ~1 ~ 0.3 0.6 0.3 0.02 20 force
kill @e[tag=gl_boss_minion,scores={gl_life=..0}]
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_fist] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_fist] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.6f,2.6f,2.6f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_hammer] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_hammer] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[3.2f,3.2f,3.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_cage] gl_life 120
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_cage] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.4f,2.4f,2.4f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_wall] gl_life 100
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_wall] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[3.2f,3.2f,3.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_claw] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_claw] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.8f,2.8f,2.8f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_crystal] gl_life 160
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_crystal] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.6f,2.6f,2.6f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_spike] gl_life 40
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_spike] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.2f,2.2f,2.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_hand] gl_life 30
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_hand] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.8f,2.8f,2.8f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_train_new] gl_life 14
execute as @e[type=minecraft:item_display,tag=gl_train_new] run data merge entity @s {start_interpolation:0,interpolation_duration:12,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,13f],scale:[2.4f,2.4f,2.4f]}}
tag @e[type=minecraft:item_display,tag=gl_train_new] remove gl_train_new
tag @e[type=minecraft:item_display,tag=gl_new] remove gl_new
scoreboard players remove @e[type=minecraft:item_display,tag=gl_construct] gl_life 1
kill @e[type=minecraft:item_display,tag=gl_construct,scores={gl_life=..0}]
