# Generated by tools/gen_corps.py
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_fist] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_fist] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.6f,2.6f,2.6f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_hammer] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_hammer] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[3.2f,3.2f,3.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_cage] gl_life 120
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_cage] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.4f,2.4f,2.4f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_wall] gl_life 100
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_wall] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[3.2f,3.2f,3.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_claw] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_claw] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.8f,2.8f,2.8f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_crystal] gl_life 160
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_crystal] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.6f,2.6f,2.6f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_spike] gl_life 40
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_spike] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.2f,2.2f,2.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_hand] gl_life 30
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_hand] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.8f,2.8f,2.8f]}}
tag @e[type=minecraft:item_display,tag=gl_new] remove gl_new
scoreboard players remove @e[type=minecraft:item_display,tag=gl_construct,tag=!gl_train_new] gl_life 1
kill @e[type=minecraft:item_display,tag=gl_construct,tag=!gl_train_new,scores={gl_life=..0}]
scoreboard players add #timer gl_life 1
execute if score #timer gl_life matches 20.. run scoreboard players set #timer gl_life 0
scoreboard players add @a[tag=gl_orange] gl_hoard 0
scoreboard players add @a[tag=gl_orange] gl_s_zombie 0
execute as @a[tag=gl_orange,scores={gl_k_zombie=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Zombie!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_zombie=1..,gl_hoard=..9}] gl_s_zombie 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_zombie=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_husk 0
execute as @a[tag=gl_orange,scores={gl_k_husk=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Husk!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_husk=1..,gl_hoard=..9}] gl_s_husk 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_husk=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_drowned 0
execute as @a[tag=gl_orange,scores={gl_k_drowned=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Drowned!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_drowned=1..,gl_hoard=..9}] gl_s_drowned 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_drowned=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_skeleton 0
execute as @a[tag=gl_orange,scores={gl_k_skeleton=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Skeleton!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_skeleton=1..,gl_hoard=..9}] gl_s_skeleton 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_skeleton=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_stray 0
execute as @a[tag=gl_orange,scores={gl_k_stray=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Stray!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_stray=1..,gl_hoard=..9}] gl_s_stray 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_stray=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_wither_skeleton 0
execute as @a[tag=gl_orange,scores={gl_k_wither_skeleton=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Wither Skeleton!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_wither_skeleton=1..,gl_hoard=..9}] gl_s_wither_skeleton 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_wither_skeleton=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_spider 0
execute as @a[tag=gl_orange,scores={gl_k_spider=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Spider!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_spider=1..,gl_hoard=..9}] gl_s_spider 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_spider=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_cave_spider 0
execute as @a[tag=gl_orange,scores={gl_k_cave_spider=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Cave Spider!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_cave_spider=1..,gl_hoard=..9}] gl_s_cave_spider 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_cave_spider=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_enderman 0
execute as @a[tag=gl_orange,scores={gl_k_enderman=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Enderman!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_enderman=1..,gl_hoard=..9}] gl_s_enderman 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_enderman=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_pillager 0
execute as @a[tag=gl_orange,scores={gl_k_pillager=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Pillager!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_pillager=1..,gl_hoard=..9}] gl_s_pillager 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_pillager=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_vindicator 0
execute as @a[tag=gl_orange,scores={gl_k_vindicator=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Vindicator!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_vindicator=1..,gl_hoard=..9}] gl_s_vindicator 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_vindicator=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_blaze 0
execute as @a[tag=gl_orange,scores={gl_k_blaze=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Blaze!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_blaze=1..,gl_hoard=..9}] gl_s_blaze 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_blaze=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_zombified_piglin 0
execute as @a[tag=gl_orange,scores={gl_k_zombified_piglin=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Zombified Piglin!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_zombified_piglin=1..,gl_hoard=..9}] gl_s_zombified_piglin 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_zombified_piglin=1..,gl_hoard=..9}] gl_hoard 1
scoreboard players add @a[tag=gl_orange] gl_s_piglin_brute 0
execute as @a[tag=gl_orange,scores={gl_k_piglin_brute=1..,gl_hoard=..9}] run title @s actionbar {"text": "Your hoard claims the Piglin Brute!", "color": "gold"}
scoreboard players add @a[tag=gl_orange,scores={gl_k_piglin_brute=1..,gl_hoard=..9}] gl_s_piglin_brute 1
scoreboard players add @a[tag=gl_orange,scores={gl_k_piglin_brute=1..,gl_hoard=..9}] gl_hoard 1
execute if score #timer gl_life matches 0 as @e[tag=gl_greed_minion] at @s run damage @s 0.01 minecraft:mob_attack by @e[type=#greenlantern:greed_prey,tag=!gl_greed_minion,distance=..16,limit=1,sort=nearest]
execute if score #timer gl_life matches 0 at @e[tag=gl_greed_minion] run particle minecraft:dust 1 0.55 0.1 1.2 ~ ~1 ~ 0.3 0.6 0.3 0 6
scoreboard players remove @e[tag=gl_greed_minion] gl_life 1
execute at @e[tag=gl_greed_minion,scores={gl_life=..0}] run particle minecraft:dust 1 0.55 0.1 2 ~ ~1 ~ 0.3 0.6 0.3 0 30
kill @e[tag=gl_greed_minion,scores={gl_life=..0}]
scoreboard players add @a[tag=gl_black] gl_dead 0
scoreboard players add @a[tag=gl_black] gl_d_zombie 0
execute as @a[tag=gl_black,scores={gl_k_zombie=1..,gl_dead=..9}] run title @s actionbar {"text": "The Zombie will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_zombie=1..,gl_dead=..9}] gl_d_zombie 1
scoreboard players add @a[tag=gl_black,scores={gl_k_zombie=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_husk 0
execute as @a[tag=gl_black,scores={gl_k_husk=1..,gl_dead=..9}] run title @s actionbar {"text": "The Husk will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_husk=1..,gl_dead=..9}] gl_d_husk 1
scoreboard players add @a[tag=gl_black,scores={gl_k_husk=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_drowned 0
execute as @a[tag=gl_black,scores={gl_k_drowned=1..,gl_dead=..9}] run title @s actionbar {"text": "The Drowned will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_drowned=1..,gl_dead=..9}] gl_d_drowned 1
scoreboard players add @a[tag=gl_black,scores={gl_k_drowned=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_skeleton 0
execute as @a[tag=gl_black,scores={gl_k_skeleton=1..,gl_dead=..9}] run title @s actionbar {"text": "The Skeleton will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_skeleton=1..,gl_dead=..9}] gl_d_skeleton 1
scoreboard players add @a[tag=gl_black,scores={gl_k_skeleton=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_stray 0
execute as @a[tag=gl_black,scores={gl_k_stray=1..,gl_dead=..9}] run title @s actionbar {"text": "The Stray will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_stray=1..,gl_dead=..9}] gl_d_stray 1
scoreboard players add @a[tag=gl_black,scores={gl_k_stray=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_wither_skeleton 0
execute as @a[tag=gl_black,scores={gl_k_wither_skeleton=1..,gl_dead=..9}] run title @s actionbar {"text": "The Wither Skeleton will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_wither_skeleton=1..,gl_dead=..9}] gl_d_wither_skeleton 1
scoreboard players add @a[tag=gl_black,scores={gl_k_wither_skeleton=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_spider 0
execute as @a[tag=gl_black,scores={gl_k_spider=1..,gl_dead=..9}] run title @s actionbar {"text": "The Spider will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_spider=1..,gl_dead=..9}] gl_d_spider 1
scoreboard players add @a[tag=gl_black,scores={gl_k_spider=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_cave_spider 0
execute as @a[tag=gl_black,scores={gl_k_cave_spider=1..,gl_dead=..9}] run title @s actionbar {"text": "The Cave Spider will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_cave_spider=1..,gl_dead=..9}] gl_d_cave_spider 1
scoreboard players add @a[tag=gl_black,scores={gl_k_cave_spider=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_enderman 0
execute as @a[tag=gl_black,scores={gl_k_enderman=1..,gl_dead=..9}] run title @s actionbar {"text": "The Enderman will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_enderman=1..,gl_dead=..9}] gl_d_enderman 1
scoreboard players add @a[tag=gl_black,scores={gl_k_enderman=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_pillager 0
execute as @a[tag=gl_black,scores={gl_k_pillager=1..,gl_dead=..9}] run title @s actionbar {"text": "The Pillager will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_pillager=1..,gl_dead=..9}] gl_d_pillager 1
scoreboard players add @a[tag=gl_black,scores={gl_k_pillager=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_vindicator 0
execute as @a[tag=gl_black,scores={gl_k_vindicator=1..,gl_dead=..9}] run title @s actionbar {"text": "The Vindicator will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_vindicator=1..,gl_dead=..9}] gl_d_vindicator 1
scoreboard players add @a[tag=gl_black,scores={gl_k_vindicator=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_blaze 0
execute as @a[tag=gl_black,scores={gl_k_blaze=1..,gl_dead=..9}] run title @s actionbar {"text": "The Blaze will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_blaze=1..,gl_dead=..9}] gl_d_blaze 1
scoreboard players add @a[tag=gl_black,scores={gl_k_blaze=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_zombified_piglin 0
execute as @a[tag=gl_black,scores={gl_k_zombified_piglin=1..,gl_dead=..9}] run title @s actionbar {"text": "The Zombified Piglin will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_zombified_piglin=1..,gl_dead=..9}] gl_d_zombified_piglin 1
scoreboard players add @a[tag=gl_black,scores={gl_k_zombified_piglin=1..,gl_dead=..9}] gl_dead 1
scoreboard players add @a[tag=gl_black] gl_d_piglin_brute 0
execute as @a[tag=gl_black,scores={gl_k_piglin_brute=1..,gl_dead=..9}] run title @s actionbar {"text": "The Piglin Brute will rise again at your command.", "color": "dark_gray"}
scoreboard players add @a[tag=gl_black,scores={gl_k_piglin_brute=1..,gl_dead=..9}] gl_d_piglin_brute 1
scoreboard players add @a[tag=gl_black,scores={gl_k_piglin_brute=1..,gl_dead=..9}] gl_dead 1
execute if score #timer gl_life matches 0 as @e[tag=gl_dead_minion] at @s run damage @s 0.01 minecraft:mob_attack by @e[type=#greenlantern:greed_prey,tag=!gl_dead_minion,distance=..16,limit=1,sort=nearest]
execute if score #timer gl_life matches 0 at @e[tag=gl_dead_minion] run particle minecraft:soul ~ ~1 ~ 0.3 0.6 0.3 0.02 6
scoreboard players remove @e[tag=gl_dead_minion] gl_life 1
execute at @e[tag=gl_dead_minion,scores={gl_life=..0}] run particle minecraft:soul ~ ~1 ~ 0.3 0.6 0.3 0.02 30
kill @e[tag=gl_dead_minion,scores={gl_life=..0}]
scoreboard players set @a[scores={gl_k_zombie=1..}] gl_k_zombie 0
scoreboard players set @a[scores={gl_k_husk=1..}] gl_k_husk 0
scoreboard players set @a[scores={gl_k_drowned=1..}] gl_k_drowned 0
scoreboard players set @a[scores={gl_k_skeleton=1..}] gl_k_skeleton 0
scoreboard players set @a[scores={gl_k_stray=1..}] gl_k_stray 0
scoreboard players set @a[scores={gl_k_wither_skeleton=1..}] gl_k_wither_skeleton 0
scoreboard players set @a[scores={gl_k_spider=1..}] gl_k_spider 0
scoreboard players set @a[scores={gl_k_cave_spider=1..}] gl_k_cave_spider 0
scoreboard players set @a[scores={gl_k_enderman=1..}] gl_k_enderman 0
scoreboard players set @a[scores={gl_k_pillager=1..}] gl_k_pillager 0
scoreboard players set @a[scores={gl_k_vindicator=1..}] gl_k_vindicator 0
scoreboard players set @a[scores={gl_k_blaze=1..}] gl_k_blaze 0
scoreboard players set @a[scores={gl_k_zombified_piglin=1..}] gl_k_zombified_piglin 0
scoreboard players set @a[scores={gl_k_piglin_brute=1..}] gl_k_piglin_brute 0
scoreboard players set @a[tag=!gl_black] gl_bkills 0
tag @a[tag=gl_look_green] remove gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
execute as @a[tag=gl_green,tag=!gl_look_green] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:green_power_battery run tag @s add gl_look_green
tag @a[tag=gl_look_yellow] remove gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
execute as @a[tag=gl_yellow,tag=!gl_look_yellow] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:yellow_power_battery run tag @s add gl_look_yellow
tag @a[tag=gl_look_red] remove gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
execute as @a[tag=gl_red,tag=!gl_look_red] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:red_power_battery run tag @s add gl_look_red
tag @a[tag=gl_look_orange] remove gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
execute as @a[tag=gl_orange,tag=!gl_look_orange] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:orange_power_battery run tag @s add gl_look_orange
tag @a[tag=gl_look_blue] remove gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
execute as @a[tag=gl_blue,tag=!gl_look_blue] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:blue_power_battery run tag @s add gl_look_blue
tag @a[tag=gl_look_violet] remove gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
execute as @a[tag=gl_violet,tag=!gl_look_violet] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:violet_power_battery run tag @s add gl_look_violet
tag @a[tag=gl_look_indigo] remove gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
execute as @a[tag=gl_indigo,tag=!gl_look_indigo] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:indigo_power_battery run tag @s add gl_look_indigo
tag @a[tag=gl_look_white] remove gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
execute as @a[tag=gl_white,tag=!gl_look_white] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:white_power_battery run tag @s add gl_look_white
tag @a[tag=gl_look_black] remove gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^0.5 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^1.0 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^1.5 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^2.0 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^2.5 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^3.0 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^3.5 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^4.0 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
execute as @a[tag=gl_black,tag=!gl_look_black] at @s anchored eyes positioned ^ ^ ^4.5 if block ~ ~ ~ greenlantern:black_power_battery run tag @s add gl_look_black
tag @a[tag=gl_near_blue] remove gl_near_blue
execute as @a[tag=gl_green] at @s if entity @a[tag=gl_blue,distance=0.1..12] run tag @s add gl_near_blue
tag @a[tag=gl_near_green] remove gl_near_green
execute as @a[tag=gl_blue] at @s if entity @a[tag=gl_green,distance=0.1..12] run tag @s add gl_near_green
scoreboard players add @a[tag=gl_green] gl_t_green 0
scoreboard players remove @a[scores={gl_t_green=1..}] gl_t_green 1
tag @a[tag=gl_green,scores={gl_t_green=..0}] remove gl_green
scoreboard players add @a[tag=gl_yellow] gl_t_yellow 0
scoreboard players remove @a[scores={gl_t_yellow=1..}] gl_t_yellow 1
tag @a[tag=gl_yellow,scores={gl_t_yellow=..0}] remove gl_yellow
scoreboard players add @a[tag=gl_red] gl_t_red 0
scoreboard players remove @a[scores={gl_t_red=1..}] gl_t_red 1
tag @a[tag=gl_red,scores={gl_t_red=..0}] remove gl_red
scoreboard players add @a[tag=gl_orange] gl_t_orange 0
scoreboard players remove @a[scores={gl_t_orange=1..}] gl_t_orange 1
tag @a[tag=gl_orange,scores={gl_t_orange=..0}] remove gl_orange
scoreboard players add @a[tag=gl_blue] gl_t_blue 0
scoreboard players remove @a[scores={gl_t_blue=1..}] gl_t_blue 1
tag @a[tag=gl_blue,scores={gl_t_blue=..0}] remove gl_blue
scoreboard players add @a[tag=gl_violet] gl_t_violet 0
scoreboard players remove @a[scores={gl_t_violet=1..}] gl_t_violet 1
tag @a[tag=gl_violet,scores={gl_t_violet=..0}] remove gl_violet
scoreboard players add @a[tag=gl_indigo] gl_t_indigo 0
scoreboard players remove @a[scores={gl_t_indigo=1..}] gl_t_indigo 1
tag @a[tag=gl_indigo,scores={gl_t_indigo=..0}] remove gl_indigo
scoreboard players add @a[tag=gl_white] gl_t_white 0
scoreboard players remove @a[scores={gl_t_white=1..}] gl_t_white 1
tag @a[tag=gl_white,scores={gl_t_white=..0}] remove gl_white
scoreboard players add @a[tag=gl_black] gl_t_black 0
scoreboard players remove @a[scores={gl_t_black=1..}] gl_t_black 1
tag @a[tag=gl_black,scores={gl_t_black=..0}] remove gl_black
tag @a[tag=gl_ring] remove gl_ring
tag @a[tag=gl_green] add gl_ring
tag @a[tag=gl_yellow] add gl_ring
tag @a[tag=gl_red] add gl_ring
tag @a[tag=gl_orange] add gl_ring
tag @a[tag=gl_blue] add gl_ring
tag @a[tag=gl_violet] add gl_ring
tag @a[tag=gl_indigo] add gl_ring
tag @a[tag=gl_white] add gl_ring
tag @a[tag=gl_black] add gl_ring
execute as @a unless score @s gl_id matches 1.. run function greenlantern:id/assign
execute as @a[tag=!gl_hasid] run function greenlantern:id/migrate
execute as @a at @s run function greenlantern:ring/bind_check
execute if score #second gl_cfg matches 5 as @a[tag=gl_ring] at @s run function greenlantern:ring/serial_check
execute if score #second gl_cfg matches 15 as @a[tag=gl_ring] at @s run function greenlantern:ring/serial_check
execute as @a[scores={gl_recall=1..}] at @s run function greenlantern:recall/trigger
execute as @a[scores={gl_forge=1..}] at @s run function greenlantern:forge/trigger
scoreboard players set @a[scores={gl_recall=..-1}] gl_recall 0
scoreboard players set @a[scores={gl_forge=..-1}] gl_forge 0
scoreboard players set @a[scores={gl_construct=..-1}] gl_construct 0
execute as @a[tag=gl_offer_any] at @s run function greenlantern:offer/follow
execute as @a[scores={gl_accept=1..}] at @s run function greenlantern:offer/accept_trigger
execute as @a[scores={gl_decline=1..}] at @s run function greenlantern:offer/decline_trigger
execute as @a[scores={gl_revoke=1..}] at @s run function greenlantern:leader/revoke_trigger
execute as @a[scores={gl_roster=1..}] run function greenlantern:leader/roster_trigger
execute as @a[scores={gl_emotions=1..}] run function greenlantern:emotion/show
scoreboard players set @a[scores={gl_emotions=1..}] gl_emotions 0
execute as @e[type=minecraft:item_display,tag=gl_leave_go] at @s run tp @s ~ ~0.6 ~
scoreboard players remove @e[type=minecraft:item_display,tag=gl_leave_go] gl_tmp 1
kill @e[type=minecraft:item_display,tag=gl_leave_go,scores={gl_tmp=..0}]
scoreboard players add #second gl_cfg 1
execute if score #second gl_cfg matches 20.. run function greenlantern:second
effect clear @a[tag=gl_green] minecraft:darkness
effect clear @a[tag=gl_green] minecraft:blindness
effect clear @a[tag=gl_green] minecraft:nausea
effect clear @a[tag=gl_red] minecraft:poison
effect clear @a[tag=gl_black] minecraft:wither
effect clear @a[tag=gl_black] minecraft:poison
execute as @a[tag=gl_indigo,scores={gl_hurt=1..}] at @s run effect give @e[type=#greenlantern:greed_prey,distance=..5] minecraft:weakness 5 1 true
scoreboard players set @a[scores={gl_hurt=1..}] gl_hurt 0
scoreboard players remove @a[scores={gl_cc_sword=1..}] gl_cc_sword 1
scoreboard players remove @a[scores={gl_cc_sword_shield=1..}] gl_cc_sword_shield 1
scoreboard players remove @a[scores={gl_cc_mace=1..}] gl_cc_mace 1
scoreboard players remove @a[scores={gl_cc_axe=1..}] gl_cc_axe 1
scoreboard players remove @a[scores={gl_cc_fist=1..}] gl_cc_fist 1
scoreboard players remove @a[scores={gl_cc_slam=1..}] gl_cc_slam 1
scoreboard players remove @a[scores={gl_cc_blast=1..}] gl_cc_blast 1
scoreboard players remove @a[scores={gl_cc_gatling=1..}] gl_cc_gatling 1
scoreboard players remove @a[scores={gl_cc_missiles=1..}] gl_cc_missiles 1
scoreboard players remove @a[scores={gl_cc_cannon=1..}] gl_cc_cannon 1
scoreboard players remove @a[scores={gl_cc_shield=1..}] gl_cc_shield 1
scoreboard players remove @a[scores={gl_cc_barrier=1..}] gl_cc_barrier 1
scoreboard players remove @a[scores={gl_cc_cage=1..}] gl_cc_cage 1
scoreboard players remove @a[scores={gl_cc_dome=1..}] gl_cc_dome 1
scoreboard players remove @a[scores={gl_cc_blocks=1..}] gl_cc_blocks 1
scoreboard players remove @a[scores={gl_cc_scuba=1..}] gl_cc_scuba 1
scoreboard players remove @a[scores={gl_cc_drill=1..}] gl_cc_drill 1
scoreboard players remove @a[scores={gl_cc_bridge=1..}] gl_cc_bridge 1
scoreboard players remove @a[scores={gl_cc_scan=1..}] gl_cc_scan 1
scoreboard players remove @a[scores={gl_cc_signature=1..}] gl_cc_signature 1
scoreboard players remove @e[type=minecraft:marker,tag=gl_hl] gl_life 1
execute as @e[type=minecraft:marker,tag=gl_hl,scores={gl_life=..0}] at @s run function greenlantern:construct/hardlight_end
scoreboard players set @e[type=minecraft:item_display,tag=gl_train_new] gl_life 14
execute as @e[type=minecraft:item_display,tag=gl_train_new] run data merge entity @s {start_interpolation:0,interpolation_duration:12,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,13f],scale:[2.4f,2.4f,2.4f]}}
tag @e[type=minecraft:item_display,tag=gl_train_new] remove gl_new
tag @e[type=minecraft:item_display,tag=gl_train_new] remove gl_train_new
execute as @a[scores={gl_construct=1..}] at @s run function greenlantern:construct/menu_trigger
