# Generated by tools/gen_corps.py
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_fist] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_fist] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.6f,2.6f,2.6f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_hammer] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_hammer] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[3.2f,3.2f,3.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_cage] gl_life 120
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_cage] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.4f,2.4f,2.4f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_wall] gl_life 100
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_wall] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[3.2f,3.2f,3.2f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_claw] gl_life 24
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_claw] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.8f,2.8f,2.8f]}}
scoreboard players set @e[type=minecraft:item_display,tag=gl_new,tag=gl_crystal] gl_life 160
execute as @e[type=minecraft:item_display,tag=gl_new,tag=gl_crystal] run data merge entity @s {start_interpolation:0,interpolation_duration:5,transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[2.6f,2.6f,2.6f]}}
tag @e[type=minecraft:item_display,tag=gl_new] remove gl_new
scoreboard players remove @e[type=minecraft:item_display,tag=gl_construct] gl_life 1
kill @e[type=minecraft:item_display,tag=gl_construct,scores={gl_life=..0}]
